export const GET_RANDOM_RECIPES = "GET_RANDOM_RECIPE";

export const GET_SEARCH_RECIPE = "GET_SEARCH_RECIPE";

export const GET_RECIPE_BY_ID = "GET_RECIPE_BY_ID";

export const SAVE_RECIPE_PROFILE = "SAVE_RECIPE_PROFILE";

export const REMOVE_SAVE_RECIPE_PROFILE = "REMOVE_SAVE_RECIPE_PROFILE";
